### ISSUE TITLE
サーバーの選定

### ISSUE THREAD

**Issue by namazu510** [nalgo-intern-2016/team-a#17]
サーバーの選定を考えよう

**Comment by namazu510** [comment]
# webサーバとアプリケーションサーバ

よくわかってないので調べたメモ
webリクエストはwebサーバーが受け取ります。そのリクエストがRailsで処理できるものであれば、webサーバーはリクエストに簡単な処理を加えてアプリケーションサーバーに渡します。アプリケーションサーバーはRackを使ってRailsアプリケーションに話しかけます。Railsアプリケーションがリクエストの処理を終えると、Railsはレスポンスをアプリケーションサーバーに返します。そして、webサーバーはあなたのアプリケーションを使っているユーザーにレスポンスを返します。

# それぞれリスト

* Apache(Webサーバ）
* Nginx  (Webサーバ）
* Passenger (Apacheに追加するmodule)
* Unicorn (Nginx+Unicornの組み合わせが一般）
* Thin (gemいじるだけでいけるらしい）
* Webrick(標準の子）

**Comment by namazu510** [comment]
AppacheでのApサーバのレスポンス比較
http://d.hatena.ne.jp/tgg/20100220/1266654598

**Comment by nocotan** [comment]
アプリケーションサーバーだけでもまあまあリクエストさばけると思いますね。
thinはリクエスト数が増えると指数的にパフォーマンスが落ちますが、今回の発表用だけならこれで十分かもしれません。

**Comment by namazu510** [comment]
サーバーの構築に時間をかけるべきじゃないだろうし　
リクエスト大量にあるわけではないと思うのでthinを使いましょう
実際に試してみますね

**Comment by nocotan** [comment]
動作確認よろしくお願いします。
![harine](https://cloud.githubusercontent.com/assets/10952293/17953261/027d083c-6aad-11e6-99fc-e00f222a3383.jpeg)

**Comment by namazu510** [comment]
thin入れてTOP画面（インデックスページ）でapache benchで速度測ってみたよ
* スループットは1.7件/s くらい
* 1リクエスト裁くのに580msくらいかかってる

ものすごく遅くない？
production環境で起動したかったんだけどなかなか起動しないからdevelopment環境で走らせたんだけどそのせいなのかな

**Comment by namazu510** [comment]
まぁテストで動けばいいからこんなもので　標準の子よりは早いしね
色々調べてやってみたさある　Windowsでサーバー動かすのはやはりダメダメね
ということでサーバーはthinさんで決定
