### ISSUE TITLE
テストについて

### ISSUE THREAD

**Issue by nocotan** [nalgo-intern-2016/team-a#18]
モデルなどの作成時に動作確認のためにユニットテストおよび統合テストを行う。

参考
http://railsdoc.com/test

**Comment by k-has-cist** [comment]
Webページのテスト仕様書ができました。
feature/sample-k-hasのTest_Caseにあります。
指摘はお手柔らかに....

**Comment by k-has-cist** [comment]
テストケースをレビューの結果をもとに訂正しました

**Comment by k-has-cist** [comment]
暫定リリースバージョンについてテストを行いました
