### ISSUE TITLE
DB調整

### ISSUE THREAD

**Issue by nocotan** [nalgo-intern-2016/team-a#19]
がんばって

**Comment by k-has-cist** [comment]
頑張ってー

**Comment by namazu510** [comment]
がんばるぞい

**Comment by k-has-cist** [comment]
GNBT～

**Comment by namazu510** [comment]
## 運動記録の登録に関する変更
* 多対多になったりどう対応づけするかとか考えるのが面倒くさいので運動記録とスケジュール間のリレーションを切ります　ページのデザイン見る限りスケジュールと運動は独立してて良さそうだしね
* モデルの定義を修正して　userの方にhas_manyを指定してあげたら対応付けができましたん
* 適当に作ったPOSTだけするHTMLフォームつくってuser_id と運動記録の必要情報載せて投げつけたらデータベスに登録してくれるアクションも一応つくれた

**Comment by nocotan** [comment]
対応有難うございます。
明日はいよいよサーバー・クライアントの連結と描画処理に入りましょう。
おろしくおねがいします。

![maxresdefault](https://cloud.githubusercontent.com/assets/10952293/17971270/17a11894-6b15-11e6-8f18-f2a788d6a751.jpg)
