### ISSUE TITLE
ファビコン追加

### ISSUE THREAD

**Issue by nocotan** [nalgo-intern-2016/team-a#24]

**Comment by namazu510** [comment]
ウォーキングしてる中年おっさんがいいとおもいます(´・ω・`)

**Comment by nocotan** [comment]
うけるけど16x16だとつぶれそう

**Comment by namazu510** [comment]
このへんの色変えればなんとか・・・(´・ω・｀)
ドット絵はきびしい
https://gyazo.com/ebbf1a71ed5b9803584fb1f392b9ca43

**Comment by nocotan** [comment]
いいねこれ
あと5日でドット絵師めざそう

**Comment by namazu510** [comment]
明日暇になったらぽちぽち打ってつくってみるよう

**Comment by nocotan** [comment]
プロドッターnamazu

**Comment by namazu510** [comment]
適当に色変えたやつ
あるくおっさん　
![あるくおっさん](http://i.imgur.com/0hUqQxf.png)

**Comment by k-has-cist** [comment]
クリボーにあたってゲームオーバーになりそう

**Comment by namazu510** [comment]
とりあえずおっさんつけといた
