### ISSUE TITLE
誤字修正

### ISSUE THREAD

**Issue by k-has-cist** [nalgo-intern-2016/team-a#27]
誤字脱字があったらここに書き込んでください

**Comment by k-has-cist** [comment]
Helpページの一部が「得られた」ではなく「えられった」になってます

**Comment by k-has-cist** [comment]
Weight less fatではなくてWeight loss fatみたいです

**Comment by k-has-cist** [comment]
Helpページ
WLFとは～です。
なのに
WLFでは～です。
になってる

**Comment by namazu510** [comment]
ここまでに見つかった分についてヘッダーフッターの共通化に併せて修正を加えました.
